packages:
  - docs
  - website
  - packages/*
  - playgrounds/*

catalog:
  '@tailwindcss/vite': ^4.1.0
  tailwindcss: ^4.1.0
  nuxt: ^3.16.2
  reka-ui: ^2.2.0
  typescript: ^5.8.3

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
