packages:
  - docs
  - website
  - packages/*
  - playgrounds/*

catalog:
  '@tailwindcss/vite': 4.0.0-beta.10
  tailwindcss: 4.0.0-beta.10
  nuxt: ^3.15.0
  reka-ui: 1.0.0-alpha.8
  typescript: ^5.6.3
