packages:
  - docs
  - website
  - packages/*
  - playgrounds/*

catalog:
  '@tailwindcss/vite': ^4.1.0
  tailwindcss: ^4.1.0
  nuxt: ^3.16.0
  reka-ui: ^2.2.0
  typescript: ^5.6.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - vue-demi
