
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'NuiLogo': typeof import("../components/NuiLogo.vue")['default']
    'NuiLogoText': typeof import("../components/NuiLogoText.vue")['default']
    'NuiPreview': typeof import("../components/NuiPreview.vue")['default']
    'NuiPreviewContainer': typeof import("../components/NuiPreviewContainer.vue")['default']
    'BaseAccordion': typeof import("../../../packages/nuxt/components/base/BaseAccordion.vue")['default']
    'BaseAvatar': typeof import("../../../packages/nuxt/components/base/BaseAvatar.vue")['default']
    'BaseAvatarGroup': typeof import("../../../packages/nuxt/components/base/BaseAvatarGroup.vue")['default']
    'BaseBreadcrumb': typeof import("../../../packages/nuxt/components/base/BaseBreadcrumb.vue")['default']
    'BaseButton': typeof import("../../../packages/nuxt/components/base/BaseButton.vue")['default']
    'BaseButtonAction': typeof import("../../../packages/nuxt/components/base/BaseButtonAction.vue")['default']
    'BaseButtonClose': typeof import("../../../packages/nuxt/components/base/BaseButtonClose.vue")['default']
    'BaseButtonGroup': typeof import("../../../packages/nuxt/components/base/BaseButtonGroup.vue")['default']
    'BaseButtonIcon': typeof import("../../../packages/nuxt/components/base/BaseButtonIcon.vue")['default']
    'BaseCard': typeof import("../../../packages/nuxt/components/base/BaseCard.vue")['default']
    'BaseDropdown': typeof import("../../../packages/nuxt/components/base/BaseDropdown.vue")['default']
    'BaseDropdownDivider': typeof import("../../../packages/nuxt/components/base/BaseDropdownDivider.vue")['default']
    'BaseDropdownItem': typeof import("../../../packages/nuxt/components/base/BaseDropdownItem.vue")['default']
    'BaseFocusLoop': typeof import("../../../packages/nuxt/components/base/BaseFocusLoop.vue")['default']
    'BaseHeading': typeof import("../../../packages/nuxt/components/base/BaseHeading.vue")['default']
    'BaseIconBox': typeof import("../../../packages/nuxt/components/base/BaseIconBox.vue")['default']
    'BaseKbd': typeof import("../../../packages/nuxt/components/base/BaseKbd.vue")['default']
    'BaseLink': typeof import("../../../packages/nuxt/components/base/BaseLink.vue")['default']
    'BaseList': typeof import("../../../packages/nuxt/components/base/BaseList.vue")['default']
    'BaseListItem': typeof import("../../../packages/nuxt/components/base/BaseListItem.vue")['default']
    'BaseMessage': typeof import("../../../packages/nuxt/components/base/BaseMessage.vue")['default']
    'BasePagination': typeof import("../../../packages/nuxt/components/base/BasePagination.vue")['default']
    'BaseParagraph': typeof import("../../../packages/nuxt/components/base/BaseParagraph.vue")['default']
    'BasePlaceholderPage': typeof import("../../../packages/nuxt/components/base/BasePlaceholderPage.vue")['default']
    'BasePlaceload': typeof import("../../../packages/nuxt/components/base/BasePlaceload.vue")['default']
    'BaseProgress': typeof import("../../../packages/nuxt/components/base/BaseProgress.vue")['default']
    'BaseProgressCircle': typeof import("../../../packages/nuxt/components/base/BaseProgressCircle.vue")['default']
    'BaseProse': typeof import("../../../packages/nuxt/components/base/BaseProse.vue")['default']
    'BaseSnack': typeof import("../../../packages/nuxt/components/base/BaseSnack.vue")['default']
    'BaseTabSlider': typeof import("../../../packages/nuxt/components/base/BaseTabSlider.vue")['default']
    'BaseTabs': typeof import("../../../packages/nuxt/components/base/BaseTabs.vue")['default']
    'BaseTag': typeof import("../../../packages/nuxt/components/base/BaseTag.vue")['default']
    'BaseText': typeof import("../../../packages/nuxt/components/base/BaseText.vue")['default']
    'BaseThemeSwitch': typeof import("../../../packages/nuxt/components/base/BaseThemeSwitch.vue")['default']
    'BaseThemeToggle': typeof import("../../../packages/nuxt/components/base/BaseThemeToggle.vue")['default']
    'IconCheck': typeof import("../../../packages/nuxt/components/icon/IconCheck.vue")['default']
    'IconCheckCircle': typeof import("../../../packages/nuxt/components/icon/IconCheckCircle.vue")['default']
    'IconChevronDown': typeof import("../../../packages/nuxt/components/icon/IconChevronDown.vue")['default']
    'IconClose': typeof import("../../../packages/nuxt/components/icon/IconClose.vue")['default']
    'IconIndeterminate': typeof import("../../../packages/nuxt/components/icon/IconIndeterminate.vue")['default']
    'IconMinus': typeof import("../../../packages/nuxt/components/icon/IconMinus.vue")['default']
    'IconMoon': typeof import("../../../packages/nuxt/components/icon/IconMoon.vue")['default']
    'IconPlus': typeof import("../../../packages/nuxt/components/icon/IconPlus.vue")['default']
    'IconSun': typeof import("../../../packages/nuxt/components/icon/IconSun.vue")['default']
    'BaseAutocomplete': typeof import("../../../packages/nuxt/components/form/BaseAutocomplete.vue")['default']
    'BaseAutocompleteItem': typeof import("../../../packages/nuxt/components/form/BaseAutocompleteItem.vue")['default']
    'BaseCheckbox': typeof import("../../../packages/nuxt/components/form/BaseCheckbox.vue")['default']
    'BaseCheckboxAnimated': typeof import("../../../packages/nuxt/components/form/BaseCheckboxAnimated.vue")['default']
    'BaseCheckboxHeadless': typeof import("../../../packages/nuxt/components/form/BaseCheckboxHeadless.vue")['default']
    'BaseFullscreenDropfile': typeof import("../../../packages/nuxt/components/form/BaseFullscreenDropfile.vue")['default']
    'BaseInput': typeof import("../../../packages/nuxt/components/form/BaseInput.vue")['default']
    'BaseInputFile': typeof import("../../../packages/nuxt/components/form/BaseInputFile.vue")['default']
    'BaseInputFileHeadless': typeof import("../../../packages/nuxt/components/form/BaseInputFileHeadless.vue")['default']
    'BaseInputHelpText': typeof import("../../../packages/nuxt/components/form/BaseInputHelpText.vue")['default']
    'BaseInputNumber': typeof import("../../../packages/nuxt/components/form/BaseInputNumber.vue")['default']
    'BaseListbox': typeof import("../../../packages/nuxt/components/form/BaseListbox.vue")['default']
    'BaseListboxItem': typeof import("../../../packages/nuxt/components/form/BaseListboxItem.vue")['default']
    'BaseRadio': typeof import("../../../packages/nuxt/components/form/BaseRadio.vue")['default']
    'BaseRadioHeadless': typeof import("../../../packages/nuxt/components/form/BaseRadioHeadless.vue")['default']
    'BaseSelect': typeof import("../../../packages/nuxt/components/form/BaseSelect.vue")['default']
    'BaseSwitchBall': typeof import("../../../packages/nuxt/components/form/BaseSwitchBall.vue")['default']
    'BaseSwitchThin': typeof import("../../../packages/nuxt/components/form/BaseSwitchThin.vue")['default']
    'BaseTextarea': typeof import("../../../packages/nuxt/components/form/BaseTextarea.vue")['default']
    'BaseTreeSelect': typeof import("../../../packages/nuxt/components/form/BaseTreeSelect.vue")['default']
    'BaseTreeSelectItem': typeof import("../../../packages/nuxt/components/form/BaseTreeSelectItem.vue")['default']
    'NuxtWelcome': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'ColorScheme': typeof import("../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'Icon': typeof import("../../../node_modules/.pnpm/@nuxt+icon@1.7.0_magicast@0.3.5_rollup@4.24.4_vite@5.4.10_@types+node@22.9.0_lightningcss@1.2_n5ugtv7olaeh5wmas4qzc3yubu/node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'NuxtPage': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyNuiLogo': typeof import("../components/NuiLogo.vue")['default']
    'LazyNuiLogoText': typeof import("../components/NuiLogoText.vue")['default']
    'LazyNuiPreview': typeof import("../components/NuiPreview.vue")['default']
    'LazyNuiPreviewContainer': typeof import("../components/NuiPreviewContainer.vue")['default']
    'LazyBaseAccordion': typeof import("../../../packages/nuxt/components/base/BaseAccordion.vue")['default']
    'LazyBaseAvatar': typeof import("../../../packages/nuxt/components/base/BaseAvatar.vue")['default']
    'LazyBaseAvatarGroup': typeof import("../../../packages/nuxt/components/base/BaseAvatarGroup.vue")['default']
    'LazyBaseBreadcrumb': typeof import("../../../packages/nuxt/components/base/BaseBreadcrumb.vue")['default']
    'LazyBaseButton': typeof import("../../../packages/nuxt/components/base/BaseButton.vue")['default']
    'LazyBaseButtonAction': typeof import("../../../packages/nuxt/components/base/BaseButtonAction.vue")['default']
    'LazyBaseButtonClose': typeof import("../../../packages/nuxt/components/base/BaseButtonClose.vue")['default']
    'LazyBaseButtonGroup': typeof import("../../../packages/nuxt/components/base/BaseButtonGroup.vue")['default']
    'LazyBaseButtonIcon': typeof import("../../../packages/nuxt/components/base/BaseButtonIcon.vue")['default']
    'LazyBaseCard': typeof import("../../../packages/nuxt/components/base/BaseCard.vue")['default']
    'LazyBaseDropdown': typeof import("../../../packages/nuxt/components/base/BaseDropdown.vue")['default']
    'LazyBaseDropdownDivider': typeof import("../../../packages/nuxt/components/base/BaseDropdownDivider.vue")['default']
    'LazyBaseDropdownItem': typeof import("../../../packages/nuxt/components/base/BaseDropdownItem.vue")['default']
    'LazyBaseFocusLoop': typeof import("../../../packages/nuxt/components/base/BaseFocusLoop.vue")['default']
    'LazyBaseHeading': typeof import("../../../packages/nuxt/components/base/BaseHeading.vue")['default']
    'LazyBaseIconBox': typeof import("../../../packages/nuxt/components/base/BaseIconBox.vue")['default']
    'LazyBaseKbd': typeof import("../../../packages/nuxt/components/base/BaseKbd.vue")['default']
    'LazyBaseLink': typeof import("../../../packages/nuxt/components/base/BaseLink.vue")['default']
    'LazyBaseList': typeof import("../../../packages/nuxt/components/base/BaseList.vue")['default']
    'LazyBaseListItem': typeof import("../../../packages/nuxt/components/base/BaseListItem.vue")['default']
    'LazyBaseMessage': typeof import("../../../packages/nuxt/components/base/BaseMessage.vue")['default']
    'LazyBasePagination': typeof import("../../../packages/nuxt/components/base/BasePagination.vue")['default']
    'LazyBaseParagraph': typeof import("../../../packages/nuxt/components/base/BaseParagraph.vue")['default']
    'LazyBasePlaceholderPage': typeof import("../../../packages/nuxt/components/base/BasePlaceholderPage.vue")['default']
    'LazyBasePlaceload': typeof import("../../../packages/nuxt/components/base/BasePlaceload.vue")['default']
    'LazyBaseProgress': typeof import("../../../packages/nuxt/components/base/BaseProgress.vue")['default']
    'LazyBaseProgressCircle': typeof import("../../../packages/nuxt/components/base/BaseProgressCircle.vue")['default']
    'LazyBaseProse': typeof import("../../../packages/nuxt/components/base/BaseProse.vue")['default']
    'LazyBaseSnack': typeof import("../../../packages/nuxt/components/base/BaseSnack.vue")['default']
    'LazyBaseTabSlider': typeof import("../../../packages/nuxt/components/base/BaseTabSlider.vue")['default']
    'LazyBaseTabs': typeof import("../../../packages/nuxt/components/base/BaseTabs.vue")['default']
    'LazyBaseTag': typeof import("../../../packages/nuxt/components/base/BaseTag.vue")['default']
    'LazyBaseText': typeof import("../../../packages/nuxt/components/base/BaseText.vue")['default']
    'LazyBaseThemeSwitch': typeof import("../../../packages/nuxt/components/base/BaseThemeSwitch.vue")['default']
    'LazyBaseThemeToggle': typeof import("../../../packages/nuxt/components/base/BaseThemeToggle.vue")['default']
    'LazyIconCheck': typeof import("../../../packages/nuxt/components/icon/IconCheck.vue")['default']
    'LazyIconCheckCircle': typeof import("../../../packages/nuxt/components/icon/IconCheckCircle.vue")['default']
    'LazyIconChevronDown': typeof import("../../../packages/nuxt/components/icon/IconChevronDown.vue")['default']
    'LazyIconClose': typeof import("../../../packages/nuxt/components/icon/IconClose.vue")['default']
    'LazyIconIndeterminate': typeof import("../../../packages/nuxt/components/icon/IconIndeterminate.vue")['default']
    'LazyIconMinus': typeof import("../../../packages/nuxt/components/icon/IconMinus.vue")['default']
    'LazyIconMoon': typeof import("../../../packages/nuxt/components/icon/IconMoon.vue")['default']
    'LazyIconPlus': typeof import("../../../packages/nuxt/components/icon/IconPlus.vue")['default']
    'LazyIconSun': typeof import("../../../packages/nuxt/components/icon/IconSun.vue")['default']
    'LazyBaseAutocomplete': typeof import("../../../packages/nuxt/components/form/BaseAutocomplete.vue")['default']
    'LazyBaseAutocompleteItem': typeof import("../../../packages/nuxt/components/form/BaseAutocompleteItem.vue")['default']
    'LazyBaseCheckbox': typeof import("../../../packages/nuxt/components/form/BaseCheckbox.vue")['default']
    'LazyBaseCheckboxAnimated': typeof import("../../../packages/nuxt/components/form/BaseCheckboxAnimated.vue")['default']
    'LazyBaseCheckboxHeadless': typeof import("../../../packages/nuxt/components/form/BaseCheckboxHeadless.vue")['default']
    'LazyBaseFullscreenDropfile': typeof import("../../../packages/nuxt/components/form/BaseFullscreenDropfile.vue")['default']
    'LazyBaseInput': typeof import("../../../packages/nuxt/components/form/BaseInput.vue")['default']
    'LazyBaseInputFile': typeof import("../../../packages/nuxt/components/form/BaseInputFile.vue")['default']
    'LazyBaseInputFileHeadless': typeof import("../../../packages/nuxt/components/form/BaseInputFileHeadless.vue")['default']
    'LazyBaseInputHelpText': typeof import("../../../packages/nuxt/components/form/BaseInputHelpText.vue")['default']
    'LazyBaseInputNumber': typeof import("../../../packages/nuxt/components/form/BaseInputNumber.vue")['default']
    'LazyBaseListbox': typeof import("../../../packages/nuxt/components/form/BaseListbox.vue")['default']
    'LazyBaseListboxItem': typeof import("../../../packages/nuxt/components/form/BaseListboxItem.vue")['default']
    'LazyBaseRadio': typeof import("../../../packages/nuxt/components/form/BaseRadio.vue")['default']
    'LazyBaseRadioHeadless': typeof import("../../../packages/nuxt/components/form/BaseRadioHeadless.vue")['default']
    'LazyBaseSelect': typeof import("../../../packages/nuxt/components/form/BaseSelect.vue")['default']
    'LazyBaseSwitchBall': typeof import("../../../packages/nuxt/components/form/BaseSwitchBall.vue")['default']
    'LazyBaseSwitchThin': typeof import("../../../packages/nuxt/components/form/BaseSwitchThin.vue")['default']
    'LazyBaseTextarea': typeof import("../../../packages/nuxt/components/form/BaseTextarea.vue")['default']
    'LazyBaseTreeSelect': typeof import("../../../packages/nuxt/components/form/BaseTreeSelect.vue")['default']
    'LazyBaseTreeSelectItem': typeof import("../../../packages/nuxt/components/form/BaseTreeSelectItem.vue")['default']
    'LazyNuxtWelcome': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyColorScheme': typeof import("../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyIcon': typeof import("../../../node_modules/.pnpm/@nuxt+icon@1.7.0_magicast@0.3.5_rollup@4.24.4_vite@5.4.10_@types+node@22.9.0_lightningcss@1.2_n5ugtv7olaeh5wmas4qzc3yubu/node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'LazyNuxtPage': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const NuiLogo: typeof import("../components/NuiLogo.vue")['default']
export const NuiLogoText: typeof import("../components/NuiLogoText.vue")['default']
export const NuiPreview: typeof import("../components/NuiPreview.vue")['default']
export const NuiPreviewContainer: typeof import("../components/NuiPreviewContainer.vue")['default']
export const BaseAccordion: typeof import("../../../packages/nuxt/components/base/BaseAccordion.vue")['default']
export const BaseAvatar: typeof import("../../../packages/nuxt/components/base/BaseAvatar.vue")['default']
export const BaseAvatarGroup: typeof import("../../../packages/nuxt/components/base/BaseAvatarGroup.vue")['default']
export const BaseBreadcrumb: typeof import("../../../packages/nuxt/components/base/BaseBreadcrumb.vue")['default']
export const BaseButton: typeof import("../../../packages/nuxt/components/base/BaseButton.vue")['default']
export const BaseButtonAction: typeof import("../../../packages/nuxt/components/base/BaseButtonAction.vue")['default']
export const BaseButtonClose: typeof import("../../../packages/nuxt/components/base/BaseButtonClose.vue")['default']
export const BaseButtonGroup: typeof import("../../../packages/nuxt/components/base/BaseButtonGroup.vue")['default']
export const BaseButtonIcon: typeof import("../../../packages/nuxt/components/base/BaseButtonIcon.vue")['default']
export const BaseCard: typeof import("../../../packages/nuxt/components/base/BaseCard.vue")['default']
export const BaseDropdown: typeof import("../../../packages/nuxt/components/base/BaseDropdown.vue")['default']
export const BaseDropdownDivider: typeof import("../../../packages/nuxt/components/base/BaseDropdownDivider.vue")['default']
export const BaseDropdownItem: typeof import("../../../packages/nuxt/components/base/BaseDropdownItem.vue")['default']
export const BaseFocusLoop: typeof import("../../../packages/nuxt/components/base/BaseFocusLoop.vue")['default']
export const BaseHeading: typeof import("../../../packages/nuxt/components/base/BaseHeading.vue")['default']
export const BaseIconBox: typeof import("../../../packages/nuxt/components/base/BaseIconBox.vue")['default']
export const BaseKbd: typeof import("../../../packages/nuxt/components/base/BaseKbd.vue")['default']
export const BaseLink: typeof import("../../../packages/nuxt/components/base/BaseLink.vue")['default']
export const BaseList: typeof import("../../../packages/nuxt/components/base/BaseList.vue")['default']
export const BaseListItem: typeof import("../../../packages/nuxt/components/base/BaseListItem.vue")['default']
export const BaseMessage: typeof import("../../../packages/nuxt/components/base/BaseMessage.vue")['default']
export const BasePagination: typeof import("../../../packages/nuxt/components/base/BasePagination.vue")['default']
export const BaseParagraph: typeof import("../../../packages/nuxt/components/base/BaseParagraph.vue")['default']
export const BasePlaceholderPage: typeof import("../../../packages/nuxt/components/base/BasePlaceholderPage.vue")['default']
export const BasePlaceload: typeof import("../../../packages/nuxt/components/base/BasePlaceload.vue")['default']
export const BaseProgress: typeof import("../../../packages/nuxt/components/base/BaseProgress.vue")['default']
export const BaseProgressCircle: typeof import("../../../packages/nuxt/components/base/BaseProgressCircle.vue")['default']
export const BaseProse: typeof import("../../../packages/nuxt/components/base/BaseProse.vue")['default']
export const BaseSnack: typeof import("../../../packages/nuxt/components/base/BaseSnack.vue")['default']
export const BaseTabSlider: typeof import("../../../packages/nuxt/components/base/BaseTabSlider.vue")['default']
export const BaseTabs: typeof import("../../../packages/nuxt/components/base/BaseTabs.vue")['default']
export const BaseTag: typeof import("../../../packages/nuxt/components/base/BaseTag.vue")['default']
export const BaseText: typeof import("../../../packages/nuxt/components/base/BaseText.vue")['default']
export const BaseThemeSwitch: typeof import("../../../packages/nuxt/components/base/BaseThemeSwitch.vue")['default']
export const BaseThemeToggle: typeof import("../../../packages/nuxt/components/base/BaseThemeToggle.vue")['default']
export const IconCheck: typeof import("../../../packages/nuxt/components/icon/IconCheck.vue")['default']
export const IconCheckCircle: typeof import("../../../packages/nuxt/components/icon/IconCheckCircle.vue")['default']
export const IconChevronDown: typeof import("../../../packages/nuxt/components/icon/IconChevronDown.vue")['default']
export const IconClose: typeof import("../../../packages/nuxt/components/icon/IconClose.vue")['default']
export const IconIndeterminate: typeof import("../../../packages/nuxt/components/icon/IconIndeterminate.vue")['default']
export const IconMinus: typeof import("../../../packages/nuxt/components/icon/IconMinus.vue")['default']
export const IconMoon: typeof import("../../../packages/nuxt/components/icon/IconMoon.vue")['default']
export const IconPlus: typeof import("../../../packages/nuxt/components/icon/IconPlus.vue")['default']
export const IconSun: typeof import("../../../packages/nuxt/components/icon/IconSun.vue")['default']
export const BaseAutocomplete: typeof import("../../../packages/nuxt/components/form/BaseAutocomplete.vue")['default']
export const BaseAutocompleteItem: typeof import("../../../packages/nuxt/components/form/BaseAutocompleteItem.vue")['default']
export const BaseCheckbox: typeof import("../../../packages/nuxt/components/form/BaseCheckbox.vue")['default']
export const BaseCheckboxAnimated: typeof import("../../../packages/nuxt/components/form/BaseCheckboxAnimated.vue")['default']
export const BaseCheckboxHeadless: typeof import("../../../packages/nuxt/components/form/BaseCheckboxHeadless.vue")['default']
export const BaseFullscreenDropfile: typeof import("../../../packages/nuxt/components/form/BaseFullscreenDropfile.vue")['default']
export const BaseInput: typeof import("../../../packages/nuxt/components/form/BaseInput.vue")['default']
export const BaseInputFile: typeof import("../../../packages/nuxt/components/form/BaseInputFile.vue")['default']
export const BaseInputFileHeadless: typeof import("../../../packages/nuxt/components/form/BaseInputFileHeadless.vue")['default']
export const BaseInputHelpText: typeof import("../../../packages/nuxt/components/form/BaseInputHelpText.vue")['default']
export const BaseInputNumber: typeof import("../../../packages/nuxt/components/form/BaseInputNumber.vue")['default']
export const BaseListbox: typeof import("../../../packages/nuxt/components/form/BaseListbox.vue")['default']
export const BaseListboxItem: typeof import("../../../packages/nuxt/components/form/BaseListboxItem.vue")['default']
export const BaseRadio: typeof import("../../../packages/nuxt/components/form/BaseRadio.vue")['default']
export const BaseRadioHeadless: typeof import("../../../packages/nuxt/components/form/BaseRadioHeadless.vue")['default']
export const BaseSelect: typeof import("../../../packages/nuxt/components/form/BaseSelect.vue")['default']
export const BaseSwitchBall: typeof import("../../../packages/nuxt/components/form/BaseSwitchBall.vue")['default']
export const BaseSwitchThin: typeof import("../../../packages/nuxt/components/form/BaseSwitchThin.vue")['default']
export const BaseTextarea: typeof import("../../../packages/nuxt/components/form/BaseTextarea.vue")['default']
export const BaseTreeSelect: typeof import("../../../packages/nuxt/components/form/BaseTreeSelect.vue")['default']
export const BaseTreeSelectItem: typeof import("../../../packages/nuxt/components/form/BaseTreeSelectItem.vue")['default']
export const NuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ColorScheme: typeof import("../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Icon: typeof import("../../../node_modules/.pnpm/@nuxt+icon@1.7.0_magicast@0.3.5_rollup@4.24.4_vite@5.4.10_@types+node@22.9.0_lightningcss@1.2_n5ugtv7olaeh5wmas4qzc3yubu/node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const NuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuiLogo: typeof import("../components/NuiLogo.vue")['default']
export const LazyNuiLogoText: typeof import("../components/NuiLogoText.vue")['default']
export const LazyNuiPreview: typeof import("../components/NuiPreview.vue")['default']
export const LazyNuiPreviewContainer: typeof import("../components/NuiPreviewContainer.vue")['default']
export const LazyBaseAccordion: typeof import("../../../packages/nuxt/components/base/BaseAccordion.vue")['default']
export const LazyBaseAvatar: typeof import("../../../packages/nuxt/components/base/BaseAvatar.vue")['default']
export const LazyBaseAvatarGroup: typeof import("../../../packages/nuxt/components/base/BaseAvatarGroup.vue")['default']
export const LazyBaseBreadcrumb: typeof import("../../../packages/nuxt/components/base/BaseBreadcrumb.vue")['default']
export const LazyBaseButton: typeof import("../../../packages/nuxt/components/base/BaseButton.vue")['default']
export const LazyBaseButtonAction: typeof import("../../../packages/nuxt/components/base/BaseButtonAction.vue")['default']
export const LazyBaseButtonClose: typeof import("../../../packages/nuxt/components/base/BaseButtonClose.vue")['default']
export const LazyBaseButtonGroup: typeof import("../../../packages/nuxt/components/base/BaseButtonGroup.vue")['default']
export const LazyBaseButtonIcon: typeof import("../../../packages/nuxt/components/base/BaseButtonIcon.vue")['default']
export const LazyBaseCard: typeof import("../../../packages/nuxt/components/base/BaseCard.vue")['default']
export const LazyBaseDropdown: typeof import("../../../packages/nuxt/components/base/BaseDropdown.vue")['default']
export const LazyBaseDropdownDivider: typeof import("../../../packages/nuxt/components/base/BaseDropdownDivider.vue")['default']
export const LazyBaseDropdownItem: typeof import("../../../packages/nuxt/components/base/BaseDropdownItem.vue")['default']
export const LazyBaseFocusLoop: typeof import("../../../packages/nuxt/components/base/BaseFocusLoop.vue")['default']
export const LazyBaseHeading: typeof import("../../../packages/nuxt/components/base/BaseHeading.vue")['default']
export const LazyBaseIconBox: typeof import("../../../packages/nuxt/components/base/BaseIconBox.vue")['default']
export const LazyBaseKbd: typeof import("../../../packages/nuxt/components/base/BaseKbd.vue")['default']
export const LazyBaseLink: typeof import("../../../packages/nuxt/components/base/BaseLink.vue")['default']
export const LazyBaseList: typeof import("../../../packages/nuxt/components/base/BaseList.vue")['default']
export const LazyBaseListItem: typeof import("../../../packages/nuxt/components/base/BaseListItem.vue")['default']
export const LazyBaseMessage: typeof import("../../../packages/nuxt/components/base/BaseMessage.vue")['default']
export const LazyBasePagination: typeof import("../../../packages/nuxt/components/base/BasePagination.vue")['default']
export const LazyBaseParagraph: typeof import("../../../packages/nuxt/components/base/BaseParagraph.vue")['default']
export const LazyBasePlaceholderPage: typeof import("../../../packages/nuxt/components/base/BasePlaceholderPage.vue")['default']
export const LazyBasePlaceload: typeof import("../../../packages/nuxt/components/base/BasePlaceload.vue")['default']
export const LazyBaseProgress: typeof import("../../../packages/nuxt/components/base/BaseProgress.vue")['default']
export const LazyBaseProgressCircle: typeof import("../../../packages/nuxt/components/base/BaseProgressCircle.vue")['default']
export const LazyBaseProse: typeof import("../../../packages/nuxt/components/base/BaseProse.vue")['default']
export const LazyBaseSnack: typeof import("../../../packages/nuxt/components/base/BaseSnack.vue")['default']
export const LazyBaseTabSlider: typeof import("../../../packages/nuxt/components/base/BaseTabSlider.vue")['default']
export const LazyBaseTabs: typeof import("../../../packages/nuxt/components/base/BaseTabs.vue")['default']
export const LazyBaseTag: typeof import("../../../packages/nuxt/components/base/BaseTag.vue")['default']
export const LazyBaseText: typeof import("../../../packages/nuxt/components/base/BaseText.vue")['default']
export const LazyBaseThemeSwitch: typeof import("../../../packages/nuxt/components/base/BaseThemeSwitch.vue")['default']
export const LazyBaseThemeToggle: typeof import("../../../packages/nuxt/components/base/BaseThemeToggle.vue")['default']
export const LazyIconCheck: typeof import("../../../packages/nuxt/components/icon/IconCheck.vue")['default']
export const LazyIconCheckCircle: typeof import("../../../packages/nuxt/components/icon/IconCheckCircle.vue")['default']
export const LazyIconChevronDown: typeof import("../../../packages/nuxt/components/icon/IconChevronDown.vue")['default']
export const LazyIconClose: typeof import("../../../packages/nuxt/components/icon/IconClose.vue")['default']
export const LazyIconIndeterminate: typeof import("../../../packages/nuxt/components/icon/IconIndeterminate.vue")['default']
export const LazyIconMinus: typeof import("../../../packages/nuxt/components/icon/IconMinus.vue")['default']
export const LazyIconMoon: typeof import("../../../packages/nuxt/components/icon/IconMoon.vue")['default']
export const LazyIconPlus: typeof import("../../../packages/nuxt/components/icon/IconPlus.vue")['default']
export const LazyIconSun: typeof import("../../../packages/nuxt/components/icon/IconSun.vue")['default']
export const LazyBaseAutocomplete: typeof import("../../../packages/nuxt/components/form/BaseAutocomplete.vue")['default']
export const LazyBaseAutocompleteItem: typeof import("../../../packages/nuxt/components/form/BaseAutocompleteItem.vue")['default']
export const LazyBaseCheckbox: typeof import("../../../packages/nuxt/components/form/BaseCheckbox.vue")['default']
export const LazyBaseCheckboxAnimated: typeof import("../../../packages/nuxt/components/form/BaseCheckboxAnimated.vue")['default']
export const LazyBaseCheckboxHeadless: typeof import("../../../packages/nuxt/components/form/BaseCheckboxHeadless.vue")['default']
export const LazyBaseFullscreenDropfile: typeof import("../../../packages/nuxt/components/form/BaseFullscreenDropfile.vue")['default']
export const LazyBaseInput: typeof import("../../../packages/nuxt/components/form/BaseInput.vue")['default']
export const LazyBaseInputFile: typeof import("../../../packages/nuxt/components/form/BaseInputFile.vue")['default']
export const LazyBaseInputFileHeadless: typeof import("../../../packages/nuxt/components/form/BaseInputFileHeadless.vue")['default']
export const LazyBaseInputHelpText: typeof import("../../../packages/nuxt/components/form/BaseInputHelpText.vue")['default']
export const LazyBaseInputNumber: typeof import("../../../packages/nuxt/components/form/BaseInputNumber.vue")['default']
export const LazyBaseListbox: typeof import("../../../packages/nuxt/components/form/BaseListbox.vue")['default']
export const LazyBaseListboxItem: typeof import("../../../packages/nuxt/components/form/BaseListboxItem.vue")['default']
export const LazyBaseRadio: typeof import("../../../packages/nuxt/components/form/BaseRadio.vue")['default']
export const LazyBaseRadioHeadless: typeof import("../../../packages/nuxt/components/form/BaseRadioHeadless.vue")['default']
export const LazyBaseSelect: typeof import("../../../packages/nuxt/components/form/BaseSelect.vue")['default']
export const LazyBaseSwitchBall: typeof import("../../../packages/nuxt/components/form/BaseSwitchBall.vue")['default']
export const LazyBaseSwitchThin: typeof import("../../../packages/nuxt/components/form/BaseSwitchThin.vue")['default']
export const LazyBaseTextarea: typeof import("../../../packages/nuxt/components/form/BaseTextarea.vue")['default']
export const LazyBaseTreeSelect: typeof import("../../../packages/nuxt/components/form/BaseTreeSelect.vue")['default']
export const LazyBaseTreeSelectItem: typeof import("../../../packages/nuxt/components/form/BaseTreeSelectItem.vue")['default']
export const LazyNuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyColorScheme: typeof import("../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyIcon: typeof import("../../../node_modules/.pnpm/@nuxt+icon@1.7.0_magicast@0.3.5_rollup@4.24.4_vite@5.4.10_@types+node@22.9.0_lightningcss@1.2_n5ugtv7olaeh5wmas4qzc3yubu/node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const LazyNuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
