<template>
  <div class="flex items-end gap-4 p-4">
    <BaseSnack
      label="Mike"
      color="default"
      size="xs"
      image="/img/people/19.jpg"
    />
    <BaseSnack
      label="Maya"
      color="default"
      size="sm"
      image="/img/people/44.jpg"
    />
    <BaseSnack
      label="John"
      color="default"
      size="md"
      image="/img/people/55.jpg"
    />
  </div>
</template>
