// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_lightningcss@1.28.1_magi_rpjfbk7wfymmtnlfvsucqgib2q/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+icon@1.7.0_magicast@0.3.5_rollup@4.24.4_vite@5.4.10_@types+node@22.9.0_lightningcss@1.2_n5ugtv7olaeh5wmas4qzc3yubu/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}