<template>
  <div class="flex flex-wrap items-end gap-4 p-4">
    <BaseAvatar
      src="/img/people/39.jpg"
      rounded="none"
      size="md"
      badge-src="/img/vector/stacks/js.svg"
    />
    <BaseAvatar
      src="/img/people/46.jpg"
      rounded="sm"
      size="md"
      badge-src="/img/vector/stacks/js.svg"
    />
    <BaseAvatar
      src="/img/people/29.jpg"
      rounded="md"
      size="md"
      badge-src="/img/vector/stacks/js.svg"
    />
    <BaseAvatar
      src="/img/people/51.jpg"
      rounded="lg"
      size="md"
      badge-src="/img/vector/stacks/js.svg"
    />
    <BaseAvatar
      src="/img/people/43.jpg"
      rounded="full"
      size="md"
      badge-src="/img/vector/stacks/js.svg"
    />
  </div>
</template>
