<template>
  <div class="flex flex-wrap items-end gap-4 p-4">
    <BaseAvatar
      src="/img/people/36.jpg"
      size="xxs"
    />
    <BaseAvatar
      src="/img/people/42.jpg"
      size="xs"
    />
    <BaseAvatar
      src="/img/people/29.jpg"
    />
    <BaseAvatar
      src="/img/people/11.jpg"
      size="md"
    />
    <BaseAvatar
      src="/img/people/3.jpg"
      size="lg"
    />
    <BaseAvatar
      src="/img/people/18.jpg"
      size="xl"
    />
    <BaseAvatar
      src="/img/people/19.jpg"
      size="2xl"
    />
  </div>
</template>
