<template>
  <div class="flex flex-wrap items-end gap-4 p-4">
    <BaseAvatar
      src="/img/people/39.jpg"
      rounded="none"
      size="md"
      mask="hex"
    />
    <BaseAvatar
      src="/img/people/46.jpg"
      rounded="none"
      size="md"
      mask="hexed"
    />
    <BaseAvatar
      src="/img/people/29.jpg"
      rounded="none"
      size="md"
      mask="blob"
    />
    <BaseAvatar
      src="/img/people/51.jpg"
      rounded="none"
      size="md"
      mask="deca"
    />
    <BaseAvatar
      src="/img/people/44.jpg"
      rounded="none"
      size="md"
      mask="diamond"
    />
  </div>
</template>
