networks:
  cssninja-services:
    external: true

services:
  nui-docs-v4:
    image: digisquad/shuriken-ui-docs:v4
    restart: unless-stopped
    networks:
      - cssninja-services
    labels:
      traefik.enable: true
      traefik.docker.network: 'cssninja-services'
      #middlewares
      traefik.http.middlewares.nui-docs-root-compress.compress: true
      traefik.http.middlewares.nui-docs-redirect.redirectregex.permanent: true
      traefik.http.middlewares.nui-docs-redirect.redirectregex.regex: '^https?://(.*)?shurikenui.com/(.*)$$'
      traefik.http.middlewares.nui-docs-redirect.redirectregex.replacement: 'https://shurikenui.com/$${2}'
      #routers
      traefik.http.routers.nui-docs-v4.entrypoints: http
      traefik.http.routers.nui-docs-v4.middlewares: nui-docs-redirect
      traefik.http.routers.nui-docs-v4.rule: 'Host(`v4.shurikenui.com`)'
      traefik.http.routers.nui-docs-v4-https.rule: 'Host(`v4.shurikenui.com`)'
      traefik.http.routers.nui-docs-v4-https.tls: true
      traefik.http.routers.nui-docs-v4-https.entrypoints: https
      traefik.http.routers.nui-docs-v4-https.tls.certresolver: http
      traefik.http.routers.nui-docs-v4-https.middlewares: nui-docs-redirect@docker
      traefik.http.routers.nui-docs-root.entrypoints: http
      traefik.http.routers.nui-docs-root.middlewares: https-redirect@docker
      traefik.http.routers.nui-docs-root.rule: 'Host(`shurikenui.com`)'
      traefik.http.routers.nui-docs-root-https.rule: 'Host(`shurikenui.com`)'
      traefik.http.routers.nui-docs-root-https.tls: true
      traefik.http.routers.nui-docs-root-https.entrypoints: https
      traefik.http.routers.nui-docs-root-https.tls.certresolver: http
      traefik.http.routers.nui-docs-root-https.middlewares: nui-docs-root-compress@docker
      traefik.http.services.nui-docs-root-https.loadbalancer.server.port: 3000
